name: Add Daily Article

on:
  push:
    branches: [add-schedule]
  schedule:
    - cron: '0 7 1-24 12 *'  # Every day at 7 AM UTC in December 1st-24th

jobs:
  add-article:
    name: Create pull request to add today's article
    permissions:
      pull-requests: write  # for repo-sync/pull-request to create a PR
      contents: write  # for repo-sync/pull-request to create a PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: coursier/cache-action@v6

      - uses: VirtusLab/scala-cli-setup@v0.1.18
        with:
          jvm: "temurin:17"

      - name: Generate todays article
        run: |
          scala-cli run .github/workflows/scripts/addDay.scala
          git config user.name gh-actions
          git config user.email actions@github.com
          git checkout -b "add-day-${{ steps.date.outputs.date }}"
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Add Article Day ${{ steps.date.outputs.date }}"
            git push --set-upstream origin add-day-${{ steps.date.outputs.date }}
          fi

      - uses: repo-sync/pull-request@v2
        with:
          source_branch: add-day-${{ steps.date.outputs.date }}
          destination_branch: website
          pr_title: Add Today's Advent of Code Article
          pr_body: |
            This PR was automatically generated to add the article of today.
          pr_assignee: ${{ github.event.head_commit.author.username }}
